### ISSUE TITLE
Problem in loading a subset of Dixit dataset

### ISSUE THREAD

**Issue by znavidi** [snap-stanford/GEARS#18]
Hi,

I am having a trouble loading a subset of the dixit dataset and get the following error. I try to follow the tutorial provided on [https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb](https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb), but have not been able to figure out the issue! Any guidance would be highly appreciated!

```
    304 gears_pert_data.prepare_split(split = 'simulation', seed = 1) # get data split with seed
    305 gears_pert_data.get_dataloader(batch_size = 32, test_batch_size = 128) # prepare data loader
pertdata.py in get_dataloader(self, batch_size, test_batch_size)
    306             for i in splits:
    307                 cell_graphs[i] = []
    308                 for p in self.set2conditions[i]:
    309                     cell_graphs[i].extend(self.dataset_processed[p])
    310 

KeyError: 'val'
```

Thanks a lot!

**Comment by yhr91** [comment]
How big is the subset that you are using? This error probably means that you have too few perturbations in your dataset to split between training, validation and test. We haven't added any error handling yet to deal with datasets with less than one perturbation condition in either train, val or test.

**Comment by yhr91** [comment]
Redundant with #19
