### ISSUE TITLE
Train/Test GEARS on One Gene Perturbation

### ISSUE THREAD

**Issue by znavidi** [snap-stanford/GEARS#19]
Hello,
I'm currently attempting to train, validate, and test GEARS using just a single gene perturbation. Unfortunately, I have not been successful in achieving this setup. From what I understand about the available split options, it seems that the described modeling scenario is not feasible with the current version of GEARS. Could you please confirm whether my understanding is correct?

```
 available_splits = ['simulation', 'simulation_single', 'combo_seen0', 
	 'combo_seen1', 'combo_seen2', 'single', 'no_test', 
	 'no_split'] 
```

Thank you.

**Comment by yhr91** [comment]
Can you describe in more detail what you mean by 

> training GEARS using just a single-gene perturbation

If you are referring to a dataset that contains multiple perturbation conditions each involving only 1 gene at a time - then this should work with the `single` split. If you mean having a dataset with just one single perturbation condition in the training set, then this is not a setting where we've tested GEARS but shouldn't be hard to incorporate.

**Comment by znavidi** [comment]
Thanks for your response!
More specifically, I mean a scenario where there is only one (the same) perturbation in both train and test sets (only one perturbation in the whole dataset). Does the current version of GEARS support modelling in such a scenario? if yes, what should be the value of the split argument?

**Comment by yhr91** [comment]
The current version of GEARS doesn't support this functionality. We plan to eventually add a 'custom' split category where users can just read in their own data split file. Can update this issue when that is added or feel free to submit a PR if you like.

**Comment by znavidi** [comment]
Thanks for the clarification!

**Comment by yhr91** [comment]
The latest version of GEARS (v0.1.2) has custom split functionality
