### ISSUE TITLE
Please give some suggestions for fly scRNA-seq analysis?

### ISSUE THREAD

**Issue by bitcometz** [snap-stanford/GEARS#23]
Hello, thanks for this great tools !!!

I want use it for fly scRNA-seq data analysis？
Should I first prepare the fly go file？
Could you give some suggestions ?

Best

**Comment by yhr91** [comment]
Hi, sorry for the very delayed response to your question. We have so far not considered modeling perturbations in different species.

You are correct that the most critical difference would be in the gene perturbation graph (i.e. The GO Graph). At the moment it is built using a GO gene annotation file called `gene2go_all.pkl`. You would need to swap this out with a file that has relevant annotation for fly and then running the code as usual should take care of the rest.

This is the function that is called to create a GO graph when one does not already exist in the model directory
https://github.com/snap-stanford/GEARS/blob/5866c6b71633812a0e957b2df90465d81a023022/gears/utils.py#L207-L236

Let me know if this doesn't work or if you have any other questions
