### ISSUE TITLE
Bug in new_data_process

### ISSUE THREAD

**Issue by pckinnunen** [snap-stanford/GEARS#24]
There is an easily fixable bug in line [254](https://github.com/snap-stanford/GEARS/blob/master/gears/pertdata.py#L254) of `gears/pertdata.py`. The line is currently:

`self.dataset_processed = self.create_dataset_file()`

However, `create_dataset_file()` doesn't return anything. Based on other usage of the `create_dataset_file()`([line 201](https://github.com/snap-stanford/GEARS/blob/master/gears/pertdata.py#L201)) the function should just be run, and it will fill in the `self.dataset_processed` instance variable. 

Just to be clear, I believe line 254 should be:

`self.create_dataset_file()`

Thanks!

**Comment by yhr91** [comment]
Thanks for pointing this out - yes this is from the latest refactor. Did this throw an error for you? I'm surprised that it passed my tests.

**Comment by pckinnunen** [comment]
I've been editing the pert_data file pretty heavily, so don't take this as gospel, but the bug happened when I ran the following commands:

```
adata = sc.read_h5ad('h5_file.h5ad') 
pert_data = PertData('./data', gene_set_path = gene_set_path)
pert_data.new_data_process(dataset_name = dataset_name, adata = adata)
```
This command would iterate through the different perturbations and then say "saving new dataset pyg object at xxx". However, the pyg file would be empty.

If I kept going with the code as in the tutorials:
```
pert_data.load(data_path = data_path)
```
Would tell me that all the perturbations were not in the GO graph, but that a local pyg dataset was detected. 
At this point, I could also `print(pert_data.dataset_processed)` and get `None`.

Then, if I run:
```
pert_data.prepare_split(split='simulation', seed = 1)
pert_data.get_dataloader(batch_size = 32, test_batch_size = 128)
```
I would finally get an error in `get_dataloader` when trying to iterate through `self.dataset_processed`. Does that help?

Thanks for getting to this so quickly, and the code overall is really easy to read and work with. I'm learning a lot using it!

**Comment by yhr91** [comment]
Thanks, yes this is helpful! I'll try to account for this when testing new code next time.

Just making sure that the latest version of the repo should be working for you now? Also I think the pip version (slightly out of date) shouldn't have this issue either.
