### ISSUE TITLE
Questions on pert_data.prepare_split

### ISSUE THREAD

**Issue by taffy-miao** [snap-stanford/GEARS#25]
Hi Team, I'm using the GEARS package to load my local dataset. I ran the code `pert_data.prepare_split(split=split, seed=1)` and found that the program add the training and testing message automatically. I wonder what parameter can let more perturb data to the training part rather than the testing or the validation part?
Thanks in advance!

**Comment by yhr91** [comment]
Did you try setting the `train_gene_set_size` argument

https://github.com/snap-stanford/GEARS/blob/3e6b0100a0ae0b63879124cff3bae1d64b8a4b46/gears/pertdata.py#L259-L266

**Comment by taffy-miao** [comment]
Thanks! This really solved my problem.
