### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by taffy-miao** [snap-stanford/GEARS#26]
Hi team, I'm using the pert_data.new_data_process and facing some problems:
`IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1143058/1783411457.py in <module>
      1 pert_data = PertData("./data/")
----> 2 pert_data.new_data_process(dataset_name = 'xialab_perturb', adata = tmp_adata)

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in new_data_process(self, dataset_name, adata)
     94         dataset_fname = os.path.join(pyg_path, 'cell_graphs.pkl')
     95         print_sys("Creating pyg object for each cell in the data...")
---> 96         self.dataset_processed = self.create_dataset_file()
     97         print_sys("Saving new dataset pyg object at " + dataset_fname)
     98         pickle.dump(self.dataset_processed, open(dataset_fname, "wb"))

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in create_dataset_file(self)
    246         dl = {}
    247         for p in tqdm(self.adata.obs['condition'].unique()):
--> 248             cell_graph_dataset = self.create_cell_graph_dataset(self.adata, p, num_samples=1)
    249             dl[p] = cell_graph_dataset
    250         return dl

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in create_cell_graph_dataset(self, split_adata, pert_category, num_samples)
    283         if pert_category != 'ctrl':
    284             # Get the indices of applied perturbation
--> 285             pert_idx = self.get_pert_idx(pert_category, adata_)
    286 
    287             # Store list of genes that are most differentially expressed for testing

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in get_pert_idx(self, pert_category, adata_)
    252     def get_pert_idx(self, pert_category, adata_):
    253         pert_idx = [np.where(p == self.gene_names)[0][0]
--> 254                     for p in pert_category.split('+')
    255                     if p != 'ctrl']
    256         return pert_idx

~/miniconda3/envs/scgpt/lib/python3.7/site-packages/gears/pertdata.py in <listcomp>(.0)
    253         pert_idx = [np.where(p == self.gene_names)[0][0]
    254                     for p in pert_category.split('+')
--> 255                     if p != 'ctrl']
    256         return pert_idx
    257 

IndexError: index 0 is out of bounds for axis 0 with size 0
`

I checked the .obs .var and .X, the type of those are the same as the adamson you provided, but it still came error

**Comment by yhr91** [comment]
I think the `condition` column in your `xialab_perturb` may not be in the right format. Can you share the output of `xialab_perturb.obs.head()`

**Comment by taffy-miao** [comment]
![image](https://github.com/snap-stanford/GEARS/assets/76729973/cd16b1d8-a320-446f-ab27-cc0759881acc)
the `single_ex_adata` is my data and the `adata` is the adamson data

**Comment by taffy-miao** [comment]
I'm facing the problem while I'm using a package named scGPT, they required using the 0.0.1 version of cell-gears. But that version can still run the adamson correctly.

**Comment by taffy-miao** [comment]
Hi Team, I've figured the problem, some of the genes that I perturbed is not contained in the .var dataframe. After I deleted those genes the model is working.

**Comment by yhr91** [comment]
Just FYI, if you switch to using GEARS v0.0.4, then it's not required that perturbed genes be in the .var dataframe
