### ISSUE TITLE
Question on data pre-processing

### ISSUE THREAD

**Issue by cbirchsy** [snap-stanford/GEARS#28]
Hi, I'm very interested in this work thanks for sharing.

I see that the code uses preprocessed h5ad files. I'd be interested to know how these data are produced from the source data e.g. [https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE133344](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE133344)

**Comment by monoplasty** [comment]
Hi, @yhr91 @kexinhuang12345 
Yes, I have the same confusion. How is the perturbation set generated, or what is the source of the perturbation set? Is it a priori knowledge of biology? I am training a large model, and I don’t know anything about how to get the data input. I hope I can get an answer! Thank you.

**Comment by yhr91** [comment]
Thanks for your question. @cbirchsy This notebook contains all the information needed for preprocessing a scanpy AnnData object in general and this is what we use for any new dataset. 

https://github.com/snap-stanford/GEARS/blob/master/demo/data_tutorial.ipynb

As for the Norman dataset that you link to, it's from an older paper so needs some extra processing. I will try to share the specific preprocessing steps for that dataset soon.

**Comment by yhr91** [comment]
@monoplasty What do you mean by perturbation set

**Comment by yhr91** [comment]
Thanks for your question. The condition column just refers to the gene that is perturbed within each cell. It is usually provided in the `.obs` metadata within the `AnnData` object.

Are you using this [link](https://plus.figshare.com/articles/dataset/_Mapping_information-rich_genotype-phenotype_landscapes_with_genome-scale_Perturb-seq_Replogle_et_al_2022_processed_Perturb-seq_datasets/20029387) to download the Replogle 2022 (Cell) dataset?

If so, you will find the condition variable under the `gene` column in `adata.obs` for any of the anndata files that are provided on that webpage.

```
      cell_barcode      gem_group   gene          gene_id  ...                                                  
 AAACCCAAGAAATCCA-27         27     NAF1  ENSG00000145414  ...      
 AAACCCAAGAACTTCC-31         31     BUB1  ENSG00000169679  ...      
```

Following this the standard GEARS preprocessing is to just convert this column to the format `<perturbed gene>+ctrl` for single-gene perturbations.

Let me know if you have any other questions.

**Comment by GordianArnav** [comment]
Hi thank you for a great paper. In your supplementary you said "This reduced the number of
perturbations in the K562 cell line from 2058 to 1092" for the Replogle et al essential dataset. Can you provide the data preprocessing notebook for that or the list of perturbations?

**Comment by yhr91** [comment]
Hi sorry for the late follow-up

- Replogle preprocessing script is available [here](https://github.com/yhr91/GEARS_misc/blob/main/data/preprocessing/Replogle_2022_preprocess.ipynb)
- There is also a cleaner implementation that I worked on for CausalBench [here](https://github.com/causalbench/causalbench/blob/master/causalscbench/data_access/utils/preprocessing.py)
