### ISSUE TITLE
How many epochs should take when training the model using the Replogle K562 essential dataset.

### ISSUE THREAD

**Issue by weizhiting** [snap-stanford/GEARS#31]
Hi, 
thanks for the great job!
Frist, how many epochs should take when training the model using K562 essential and RPE1 datasets? will the larger the performance is better? How many epochs you set in your current study?

Second, at present the perturb-seq dataset is usually small which only with tens of perturbations? So, I want to ask how many perturbations the model usually need to get a satisfactory performance. To put it more clearly, if I train gears using a dataset only with 20s single gene perturbations, will it get a satisfactory performance?

Thanks for your patience！

**Comment by yhr91** [comment]
Thanks for your questions!

We recommend training for 15 epochs. We've not observed significantly better performance training beyond this point.

With smaller datasets, the performance generally does suffer, especially in the multi-gene setting. I recommend plotting out perturbation results for held out genes to assess if you find it satisfactory.
