### ISSUE TITLE
Very long import time

### ISSUE THREAD

**Issue by dzyim** [snap-stanford/GEARS#34]
The package `gears` takes too much time to import. (`__version__ = '0.0.3'`)

```
$time python -c 'from gears import PertData'

real    1m37.423s
user    0m14.010s
sys     0m5.412s
```

```
$time python -c 'import torch'

real    0m18.923s
user    0m2.117s
sys     0m1.732s
```

**Comment by yhr91** [comment]
Thanks for sharing. It doesn't seem significantly long but please let us know if you have suggestions to speed up the import
