### ISSUE TITLE
error: model_initialize() got an unexpected keyword argument 'cell_fitness_pred' when running "Using Trained Model" tutorial

### ISSUE THREAD

**Issue by xwanaf** [snap-stanford/GEARS#37]
Hi,

Thank you for your wonderful work! However, when I follow the tutorial "Using Trained Model", I encounter the error 
```
model_initialize() got an unexpected keyword argument 'cell_fitness_pred'
```
Perhaps this is because of the differences in version of gears. I found that the parameter ```cell_fitness_pred``` disappeared in the current version. Can you give some suggestions for this situation?

**Comment by docmab23** [comment]
Tried downgrading the version to `0.0.1`, that didn't help. Also, digressing a bit, what's the difference betweeen `predict` and `GI_predict`

**Comment by yhr91** [comment]
Thanks for your comment! The Colab works if you downgrade to `0.0.4`. I've updated the Colab, let me know if it still doesn't work for you

**Comment by yhr91** [comment]
The Colab has now been updated and works out of the box with the up to date version of GEARS. No downgrading needed
