### ISSUE TITLE
No file in https://dataverse.harvard.edu/api/accsess/datafile/6934319

### ISSUE THREAD

**Issue by hzlllll** [snap-stanford/GEARS#38]
Hello, I try to use the tutorial but i can't find the go_essential_all in https://dataverse.harvard.edu/api/accsess/datafile/6934319
![image](https://github.com/snap-stanford/GEARS/assets/38622091/25e010af-9850-48dd-bffb-2bcc02ee28ca)

Here is the response:
![image](https://github.com/snap-stanford/GEARS/assets/38622091/4d9827d7-68ad-4cd7-a306-f702f08c71f7)
May you give another valid  file link? Thanks!

**Comment by yhr91** [comment]
Seems to be downloading for me using the link 

https://github.com/snap-stanford/GEARS/blob/5866c6b71633812a0e957b2df90465d81a023022/gears/utils.py#L249C28-L249C85

The link that you share in your comment has a typo. It should be `access` not `accsess`

**Comment by hzlllll** [comment]
> Seems to be downloading for me using the link
> 
> https://github.com/snap-stanford/GEARS/blob/5866c6b71633812a0e957b2df90465d81a023022/gears/utils.py#L249
> 
> The link that you share in your comment has a typo. It should be `access` not `accsess`
Sorry, I find the link in the code but may forget to copy it! Thanks!
