### ISSUE TITLE
Demo notebook raises gradient error for torch 1.12

### ISSUE THREAD

**Issue by subercui** [snap-stanford/GEARS#4]
Hi, I'm using torch 1.12.0 and python 3.9, and when I run the demo notebook https://github.com/snap-stanford/GEARS/blob/master/demo/model_tutorial.ipynb, it raises this error when running `gears_model.train`.

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> File <ipython-input-1-48e0c827b980>:1, in <cell line: 1>()
> ----> 1 gears_model.train(epochs = 1, lr = 1e-3)
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/gears/gears.py:298, in GEARS.train(self, epochs, lr, weight_decay)
>     293     pred = self.model(batch)
>     294     loss = loss_fct(pred, y, batch.pert,
>     295                   ctrl = self.ctrl_expression, 
>     296                   dict_filter = self.dict_filter,
>     297                   direction_lambda = self.config['direction_lambda'])
> --> 298 loss.backward()
>     299 nn.utils.clip_grad_value_(self.model.parameters(), clip_value=1.0)
>     300 optimizer.step()
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/torch/_tensor.py:396, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
>     387 if has_torch_function_unary(self):
>     388     return handle_torch_function(
>     389         Tensor.backward,
>     390         (self,),
>    (...)
>     394         create_graph=create_graph,
>     395         inputs=inputs)
> --> 396 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/torch/autograd/__init__.py:173, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
>     168     retain_graph = create_graph
>     170 # The reason we repeat same the comment below is that
>     171 # some Python versions print out the first line of a multi-line function
>     172 # calls in the traceback and some print out the last line
> --> 173 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
>     174     tensors, grad_tensors_, retain_graph, create_graph, inputs,
>     175     allow_unreachable=True, accumulate_grad=True)
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [161440, 64]], which is output 0 of ReluBackward0, is at version 76; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Input In [1], in <cell line: 1>()
> ----> 1 get_ipython().run_line_magic('run', 'gears_perturb.ipynb')
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2305, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
>    2303     kwargs['local_ns'] = self.get_local_scope(stack_depth)
>    2304 with self.builtin_trap:
> -> 2305     result = fn(*args, **kwargs)
>    2306 return result
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/IPython/core/magics/execution.py:717, in ExecutionMagics.run(self, parameter_s, runner, file_finder)
>     715     with preserve_keys(self.shell.user_ns, '__file__'):
>     716         self.shell.user_ns['__file__'] = filename
> --> 717         self.shell.safe_execfile_ipy(filename, raise_exceptions=True)
>     718     return
>     720 # Control the response to exit() calls made by the script being run
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2811, in InteractiveShell.safe_execfile_ipy(self, fname, shell_futures, raise_exceptions)
>    2809 result = self.run_cell(cell, silent=True, shell_futures=shell_futures)
>    2810 if raise_exceptions:
> -> 2811     result.raise_error()
>    2812 elif not result.success:
>    2813     break
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/IPython/core/interactiveshell.py:251, in ExecutionResult.raise_error(self)
>     249     raise self.error_before_exec
>     250 if self.error_in_exec is not None:
> --> 251     raise self.error_in_exec
> 
>     [... skipping hidden 1 frame]
> 
> File <ipython-input-1-48e0c827b980>:1, in <cell line: 1>()
> ----> 1 gears_model.train(epochs = 1, lr = 1e-3)
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/gears/gears.py:298, in GEARS.train(self, epochs, lr, weight_decay)
>     293     pred = self.model(batch)
>     294     loss = loss_fct(pred, y, batch.pert,
>     295                   ctrl = self.ctrl_expression, 
>     296                   dict_filter = self.dict_filter,
>     297                   direction_lambda = self.config['direction_lambda'])
> --> 298 loss.backward()
>     299 nn.utils.clip_grad_value_(self.model.parameters(), clip_value=1.0)
>     300 optimizer.step()
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/torch/_tensor.py:396, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
>     387 if has_torch_function_unary(self):
>     388     return handle_torch_function(
>     389         Tensor.backward,
>     390         (self,),
>    (...)
>     394         create_graph=create_graph,
>     395         inputs=inputs)
> --> 396 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> 
> File /anaconda/envs/Gears/lib/python3.9/site-packages/torch/autograd/__init__.py:173, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
>     168     retain_graph = create_graph
>     170 # The reason we repeat same the comment below is that
>     171 # some Python versions print out the first line of a multi-line function
>     172 # calls in the traceback and some print out the last line
> --> 173 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
>     174     tensors, grad_tensors_, retain_graph, create_graph, inputs,
>     175     allow_unreachable=True, accumulate_grad=True)
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [161440, 64]], which is output 0 of ReluBackward0, is at version 76; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

I think this is related to some inplace operation in the model.

**Comment by WhirlFirst** [comment]
I have the same error. Any solution?

**Comment by kexinhuang12345** [comment]
Hi! For a temporary solution, could you try downgrade torch to 1.9.0? we are working on finding where this issue comes from in the most recent torch version.

**Comment by kexinhuang12345** [comment]
Hi! It should be fixed now: https://github.com/snap-stanford/GEARS/commit/b2ab2ce3d8ec4d01177cf990bc3e4cf33229c708 
you can also do pip install --upgrade with the latest verison!
