### ISSUE TITLE
About the preparation of split

### ISSUE THREAD

**Issue by GoldenRain-Su** [snap-stanford/GEARS#40]
Hello,  dear developers.
I run the code as below two times, but I think there are something went wrong about the file generation in the split prepare step

`pert_data = PertData('./data')`
`pert_data.load(data_name = 'norman')`
`pert_data.prepare_split(split = 'simulation', seed = 1)`
`pert_data.get_dataloader(batch_size = 32, test_batch_size = 128)`

And the error message is shown as below:
![image](https://github.com/snap-stanford/GEARS/assets/84309437/f21b3d45-0175-4185-b533-3a12253ec5cc)
So I want to know how to fix that problem. Thanks for your jobs!

**Comment by yhr91** [comment]
Thanks for your question! I just ran the code you shared and it worked for me. Can you please share the version of GEARS you are using and the full script. Thanks

**Comment by GoldenRain-Su** [comment]
> Thanks for your question! I just ran the code you shared and it worked for me. Can you please share the version of GEARS you are using and the full script. Thanks

The version of cell-gears is 0.1.1 and the full script is shown as below:
![image](https://github.com/snap-stanford/GEARS/assets/84309437/d924ec43-fa94-4b0a-8559-42ccca52ee10)
Do you think it is a mistake about syntax of path?

**Comment by AtheerAS** [comment]
Hi,
I had have the same issue with version 0.1.2. Any clue?

Thank you for developing this great package!
