### ISSUE TITLE
prediction interpretation

### ISSUE THREAD

**Issue by Gianl-msi** [snap-stanford/GEARS#46]
The prediction tutorial notebook generates values between 0 and 5. Are those absolute expression changes? Or expression values post perturbation?
If those are the final expression value, what's the fastest way to retrieve the unperturbed values?

**Comment by yhr91** [comment]
Thanks for your question. The output of the predict function is expression values post perturbation.

To retrieve unperturbed values you can simply call `gears_model.ctrl_expression` for average unperturbed state or `gears_model.ctrl_adata` for gene expression values for all control cells from the original dataset.
