### ISSUE TITLE
Interpretation of Prediction

### ISSUE THREAD

**Issue by uddamvathanak** [snap-stanford/GEARS#47]
Hi author,

I have run the tutorial to test out on GEARS model and what I found is that the output of the prediction is not a gene expression in post perturbation and instead it is just a gene vector.

May I know how to obtained the post perturbation gene expression?

Thanks.

**Comment by yhr91** [comment]
Thanks for your question. Can you share what you mean by a 'gene vector'? GEARS outputs a vector of post-perturbation gene expression values

**Comment by uddamvathanak** [comment]
what I meant by gene vector is that the output is in the shape of (1, number of genes) instead of (number of cell, nunber of genes).

I would imagine that the output is for each cell instead like post perturbation gene expression in shape of (cell, gene)

Is my answer clear enough?

Thanks :D

**Comment by yhr91** [comment]
Thanks for your question. The response should be in the shape of `(number of perturbation categories, number of genes)`. This is because GEARS predicts the average perturbation effects for a specific perturbation category and does not predict perturbation effects at the level of individual cells.

**Comment by uddamvathanak** [comment]
Thanks it clear my doubt. Cheer :D
