### ISSUE TITLE
A question about directional loss.

### ISSUE THREAD

**Issue by Bunnybeibei** [snap-stanford/GEARS#52]
Thank you for your impressive work, especially some designs on losses. However, I found the sign function used in the directional loss to be non-derivable, resulting in zero gradients. How does this loss work in the final result?

**Comment by yhr91** [comment]
Thanks for your comments. Yes, you are correct that the sign function is not differentiable and this is an error. One way to circumvent this is to use the `tanh` function. We plan to update the repo once we've done some systematic tests but so far it looks like this improves performance slightly.

More discussion here: https://github.com/snap-stanford/GEARS/issues/36
