### ISSUE TITLE
KeyError: 'val'

### ISSUE THREAD

**Issue by yanwuanxin** [snap-stanford/GEARS#56]
Hi, thanks for sharing. I encountered the following error：
<img width="713" alt="b80ee0de2f44c4405f0b19dce31ab14" src="https://github.com/snap-stanford/GEARS/assets/61311726/aee0a45d-ef9a-4f61-89b4-bfe89bdf252c">

my adata.obs:
![image](https://github.com/snap-stanford/GEARS/assets/61311726/c1e963ee-60a9-4355-9c04-9b1ec1ec7804)

**Comment by yhr91** [comment]
This probably means there's an error in your split. How many perturbations are there in your dataset and which split did you pick

**Comment by yanwuanxin** [comment]
condition/ cell_type variable as follow:
![image](https://github.com/snap-stanford/GEARS/assets/61311726/a3ca9414-2582-4bcf-86d6-0968849a24c0)

 I randomly created the condition variable, I'm not quite sure about condition variable

**Comment by yanwuanxin** [comment]
`pert_data.prepare_split(split = 'simulation', seed = 1)` 
 I'm not sure how to choose `split ` parameter either

**Comment by yhr91** [comment]
There area  few issues here:

Those are too few perturbation categories for the model to perform the default 'simulation' split. I also wouldn't recommend training GEARS on only a single perturbation under any split. 

Lastly, the current version of GEARS is not set up to predict effects across multiple cell types as this is not accounted for in the training data.

**Comment by yanwuanxin** [comment]
Thank you very much, i will try to modify the adata according to your suggestions.
