### ISSUE TITLE
result of gears_model.GI_predict: ['mag', 'dcor', 'corr_fit', 'dominance', 'eq_contr']

### ISSUE THREAD

**Issue by yanwuanxin** [snap-stanford/GEARS#59]
result of `gears_model.GI_predict` contain 'mag', 'dcor', 'corr_fit', 'dominance', 'eq_contr', legend of Figure5b of paper are Synergy/ Suppression/ Neomorphism/ Epistasis/ Redundancy, how did they match?

![image](https://github.com/snap-stanford/GEARS/assets/61311726/10aaa888-e01d-4b84-ba8f-ca1d8eb3c233)

**Comment by yhr91** [comment]
Please see SI Note 16 in the paper

<img width="596" alt="Screenshot 2024-03-26 at 2 45 17 AM" src="https://github.com/snap-stanford/GEARS/assets/12547304/0002da70-bc53-4c1d-8f53-b333d7ced764">
