### ISSUE TITLE
custom GO graph location

### ISSUE THREAD

**Issue by Jiahao-Gao** [snap-stanford/GEARS#60]
line212 in utils.py
`fname` under `make_GO` should use `data_path` variable, not hardcoded `./data/`

**Comment by yanwuanxin** [comment]
I encountered an error at `model_initialize > get_similarity_network > make_GO`, when run `pert_data = PertData(data_path = outdir, default_pert_graph = False)`. I made the following modifications, error message did not appear.
![image](https://github.com/snap-stanford/GEARS/assets/61311726/ad0dfdc0-49c9-44e3-b214-4e77f20ee1c6)

**Comment by yanwuanxin** [comment]
I encountered an error at `model_initialize > get_similarity_network > make_GO`，after run pert_data = PertData(data_path = outdir, default_pert_graph = False). I made the following modifications, error message did not appear.
![image](https://github.com/snap-stanford/GEARS/assets/61311726/99c31134-ee46-4d6a-bf4c-b9dae3f5a143)
