### ISSUE TITLE
differences between papers and implementations

### ISSUE THREAD

**Issue by sheunbaek** [snap-stanford/GEARS#61]
Hi, thanks for sharing this greatful study!

I'm trying to implement your code based on norman data now, and I have 2 questions.

1. The performance is better than the paper. In the paper, "pearson correlation" is between 0.5 and 0.6, but when I actually implemented it, "test_de_pearson" was about 0.84. And the performance you presented in "demo/model_tutorial.ipynb" also looks about 0.83 based on seen0, seen1. May I know why there is a difference?
![image](https://github.com/snap-stanford/GEARS/assets/139978758/98691484-2783-43f5-b826-4b79c6068df3)

2. In the paper, it says that normal data is a description of K562 cells, but the data downloaded from the link in the code is A549. Can you tell me why there is a difference?
![image](https://github.com/snap-stanford/GEARS/assets/139978758/7989cc65-52a9-441b-aae0-34a15d1743a7)

Please let me know if my question is weird or if you have any additional comments.
Thank you very much in advance.

**Comment by yhr91** [comment]
Thanks for your question

1. `pearson_de` is not the metric we report in the paper. We report `pearson_delta` which looks at the Pearson correlation between the predicted change in expression and the true change in expression. 
<img width="593" alt="Screenshot 2024-04-13 at 5 47 48 PM" src="https://github.com/snap-stanford/GEARS/assets/12547304/cd4c7390-3113-4661-ae32-8f108af18a60">

On the other hand, `pearson_de` looks at the Pearson correlation between the predicted absolute post-perturbation gene expression and the true absolute post-perturbation expression value, only limited to the most differentially expressed genes.  More information on metrics in the paper can be found in Supplementary Table 1.

2. GEARS currently doesn't make any use of `cell_type` information so this column is set arbitrarily and does not impact model training in any way.
