### ISSUE TITLE
Question about how to generate condition colname?

### ISSUE THREAD

**Issue by yanwuanxin** [snap-stanford/GEARS#63]
Hi Yusuf et al.

Assuming my adata has 3000 cells, and i want to perturba two genes(geneA & geneB, i know it's not well to train models with few genes). is the following code reasonable.

```
tem = []
tem.extend(list(np.repeat("geneA+ctrl", 1000)))
tem.extend(list(np.repeat("geneB+ctrl", 1000)))
tem.extend(list(np.repeat("ctrl", 1000)))
adata.obs = adata.obs.assign(condition = tem)
```

3000 cells, 1000 cells set as ctrl, and the remaining cells are evenly distributed to geneA and geneB, is it okay to do this?

**Comment by yhr91** [comment]
Syntactically this is fine, but may not be a strong model

**Comment by yanwuanxin** [comment]
can I use this code to generate `condition`, without considering other factors.

**Comment by yanwuanxin** [comment]
without considering other factors, can I use above code generate `condition` under this assumption？

**Comment by yanwuanxin** [comment]
your data:
<img width="311" alt="b8430bbce7a18b1207c0412dc29caed" src="https://github.com/snap-stanford/GEARS/assets/61311726/f23252ba-7af6-4e94-8b0c-80590e9da07d">

my data:
<img width="341" alt="d0faac61939364172f8d0d184a8266e" src="https://github.com/snap-stanford/GEARS/assets/61311726/38e54fb3-243b-475e-9d3b-bb0511afba9f">

in one of your `adata.obs.condition`, the distribution of number of perturbations and 'ctrl' seems to have no pattern at all; 
in my own `adata.obs.condition`, i use the following code generate `condition`, cell number of perturbations and 'ctrl' are almost equal;

`
geneUse = ["SELENOM","SELENOW","BSCL2","ACY1","RAB5IF","BEX3","SELENOP","SELENOM+SELENOW","SELENOM+SELENOP","SELENOW+SELENOP"]
n_count = math.floor(adata.obs.shape[0]/(len(geneUse)+1))

a = []
for g in geneUse:
  if "+" in g:
    a.extend(list(np.repeat(g, n_count)))
  else:
    a.extend(list(np.repeat(g+"+ctrl", n_count)))
a.extend(list(np.repeat("ctrl", (adata.obs.shape[0]-n_count*len(geneUse)))))
adata.obs = adata.obs.assign(condition = a)
`
my question:  
1. can the above code be used to generate `condition`?
2. does the distribution of cell numbers of perturbations affect the results, if so, how to determine the distribution of cell numbers of perturbations?

looking forward to your reply.

**Comment by yanwuanxin** [comment]
your data:
<img width="311" alt="b8430bbce7a18b1207c0412dc29caed" src="https://github.com/snap-stanford/GEARS/assets/61311726/118d7812-b4dd-47b8-9cd5-ed330e2433c1">


my data:
<img width="341" alt="d0faac61939364172f8d0d184a8266e" src="https://github.com/snap-stanford/GEARS/assets/61311726/c44619e9-cfa4-4004-b6b3-8924c2c7f122">

in one of your `adata.obs.condition`, the distribution of number of perturbations and 'ctrl' seems to have no pattern at all;
in my own `adata.obs.condition`, i use the following code generate `condition`, cell number of perturbations and 'ctrl' are almost equal;

![image](https://github.com/snap-stanford/GEARS/assets/61311726/4102f0c1-8dec-4dcb-a1fe-8fdc61258106)

my question:
1. can the above code be used to generate `condition`?
2. does the distribution of cell numbers of perturbations affect the results, if so, how to determine the distribution of cell numbers of perturbations?

looking forward to your reply.
