### ISSUE TITLE
Are there pretrained weights available?

### ISSUE THREAD

**Issue by jamesbraza** [snap-stanford/GEARS#67]
`GEARS.load_pretrained` loads in a `model.pt` to `GEARS.model`.

Where can one find that `model.pt` file? Is there a pre-trained variant available somewhere (e.g. Hugging Face)?

**Comment by yhr91** [comment]
Yes, there is a pretrained model available through this [Colab notebook](https://colab.research.google.com/drive/11LlzGEUGoBk_Uj6DzlzizAeWse5_E9MK?usp=sharing)
