### ISSUE TITLE
Duplicated gene names in replogle_k562_essential

### ISSUE THREAD

**Issue by zhan8855** [snap-stanford/GEARS#68]
Hi, I have the following error,

```
pert_data = PertData('./data')
pert_data.load(data_name='replogle_k562_essential')
gene_name = pert_data.adata.var['gene_name'].tolist()

assert len(gene_name) == len(set(gene_name))
>>> AssertionError
```

**Comment by yhr91** [comment]
Yes, I believe there is one gene name that is repeated twice in this dataset. This doesn't impact the model because it mainly relies on gene indices during training and prediction.

**Comment by yhr91** [comment]
Yes, gene names are arbitrary constructs given to segments of the DNA. For example, often multiple ENSEMBL ids map to similar gene names

**Comment by zhan8855** [comment]
Thank you very much!!
