### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by chocolate9624** [snap-stanford/GEARS#7]
Thanks for your great contribution! 

I have two questions about the implementation. 
1,
> https://github.com/snap-stanford/GEARS/blob/master/gears/model.py#L146-L151
If the batch size = 2 and len(list(pert_track.values()))==2, single perturbation will be fed into MLP. 
I also find not all the training examples in one batch have two perturbations. 

2,
> https://github.com/snap-stanford/GEARS/blob/master/gears/model.py#L139-L144
As the 'j' in these lines is a tensor, not an integer, this line
`pert_track[j] = pert_track[j] + pert_global_emb[pert_index[1][i]]` 
is not executed during training process. 
So these two perturbations for one sample are not added together?

**Comment by yhr91** [comment]
Thanks for your questions!

1. If batch_size is 2, then the model resorts to default behavior in line 151 and both pert_track.values() are fed into the MLP. I don't understand what you mean by the second part of your question.

2. Thanks for pointing this out! Yes that’s an error and _j_ should not be a Tensor. The error occurred as we were transferring the code over to the new base. In the [original codebase used to run the experiments](https://github.com/yhr91/gears_misc/blob/04252979b13282c7cacf99e864b8d3d2fcb88f4c/legacy/model.py#L651-L654) in the preprint, _j_ was converted to an int 

```
if j.item() in pert_track:
          pert_track[j.item()] = torch.stack((pert_track[j.item()], pert_global_emb[pert_index[1][i]]))
```
