### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by XinMakise** [snap-stanford/GEARS#73]
When I want to create a new custom dataset, I encounter the following error. Even when I switch to other datasets, the same error still occurs.
![image](https://github.com/snap-stanford/GEARS/assets/66819616/925ca967-ed91-43ac-bc10-0f65e3970040)

**Comment by XinMakise** [comment]
> W

**Comment by adyteaS** [comment]
Hi @XinMakise , could you please share your solution? 
I'm facing a similar error.
