### ISSUE TITLE
Beginner question: GEARS on un-perturbed data

### ISSUE THREAD

**Issue by bioinfonewguy** [snap-stanford/GEARS#74]
Hello,

I am new to bioinformatics and these work flows in general, but I am attempting to learn by working through different tools. 

I loved the GEARS paper, and I am trying to wrap my head around how it could be used.

Do I have to initially have a dataset which contains perturbations? Or could I pull a single celltype from a source like CellxGene, and perform in silico perturbations of interest? I know that's a beginner question, and apologize if it's too basic.

Thank you for your time!

**Comment by yhr91** [comment]
Hi, thanks for your question. Unfortunately, the current version of GEARS has not been designed for training on unperturbed data. We recommend training on data from perturbed cells, where the cell type and experiment type of the training data match those that are desired at the time of inference.
