### ISSUE TITLE
Question about "Using Trained Model"

### ISSUE THREAD

**Issue by incase-1** [snap-stanford/GEARS#77]
Hi Team,
I used the "Using Trained Model" code from your GitHub repository. When running "gears_model.predict([['VEGFR3']])", I encountered an error stating that "VEGFR3 is not in the perturbation graph. Please select from GEARS.pert_list!" As a result, I created a new gene list and passed it to the gene_set_path parameter. Do I need to retrain the model in this case?

**Comment by yhr91** [comment]
Yes, for genes that were not present in the perturbation graph at the time of training, you would have to have to include them in the perturbation graph and re-train the model. Otherwise, the prediction will probably just be random.
