### ISSUE TITLE
How is the adamson data generated?

### ISSUE THREAD

**Issue by YOU-k** [snap-stanford/GEARS#83]
Hi there, thanks for the great work. I tried with Adamson data, but the data is quite different from what I downloaded from the original paper. The number of controls, sgRNAs, etc., are all different. Could you please tell me how the preprocessing goes to get the expected data? Cheers, Yue

**Comment by yhr91** [comment]
Sorry for the delay in responding. I believe this [notebook](https://github.com/yhr91/GEARS_misc/blob/main/data/preprocessing/Adamson2016.ipynb) should contain all the steps needed for preprocessing the Adamson dataset, but feel free to re-open this issue if anything is missing.
