### ISSUE TITLE
Question about loss function of direction

### ISSUE THREAD

**Issue by ChangxiChi** [snap-stanford/GEARS#86]
In direction loss function, “torch.sign” will result in gradients being almost zero, which means that while it won't throw an error, it essentially has no effect in practice. If there are any mistakes, please point them out.

**Comment by yhr91** [comment]
Thanks for your comments. Yes, you are correct that the sign function is not differentiable and this is an error. One way to circumvent this is to use the tanh function. We plan to update the repo once we've done some systematic tests but so far it looks like this improves performance slightly.

More discussion here: https://github.com/snap-stanford/GEARS/issues/36
