### ISSUE TITLE
uncertainty score question

### ISSUE THREAD

**Issue by ernesto-iacucci** [snap-stanford/GEARS#88]
Hi, I looked up help for the gears_model.predict() function and got back the below information, is this info out of date as i it doesn't return the uncertainty score for me?

Help on function predict in module gears.gears:

predict(self, pert_list)
    Predict the transcriptome given a list of genes/gene combinations being
    perturbed
    
    Parameters
    ----------
    pert_list: list
        list of genes/gene combiantions to be perturbed
    
    Returns
    -------
    results_pred: dict
        dictionary of predicted transcriptome
    results_logvar: dict
        dictionary of uncertainty score

**Comment by yhr91** [comment]
Did you set the `uncertainty` flag to `True` when [initializing the model](https://github.com/snap-stanford/GEARS/blob/6575a8f4e780814badbcff75a9dfd53b91e47218/gears/gears.py#L129)?

**Comment by ernesto-iacucci** [comment]
I didn't, thank you for the clarification
